Alest/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

account/urls.py
from django.urls import path
from .views import login_view, logout_view, register

app_name = 'accounts'

urlpatterns = [
    path("login/", login_view, name="login"),
    path("logout/", logout_view, name="logout"),
    path("register/", register, name="register"),
]

home/urls.py
from django.urls import path
from .views import home, about

app_name = 'home'

urlpatterns = [
    path("", home, name="home"),
    path("about/", about, name="about"),
]

account/models.py
from django.db import models

# Create your models here.

home/models.py
from django.db import models

# Create your models here.

account/views.py
from multiprocessing import context
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
# from home.apps.homeConfig import urls

# Create your views here.

def login_view(request):
    if request.method == "POST":
       username = request.POST.get("username")
       password = request.POST.get("password")
       user = authenticate(request, username=username, password=password)
       if user is not None:
           login(request,user)
           return redirect("home:home")
    return render(request, "home/login.html")

def register(request):
    if request.method == "POST":
        username = request.POST.get("username")
        email = request.POST.get("email")
        fname = request.POST.get("fname")
        lname = request.POST.get("lname")
        password1 = request.POST.get("password")
        password2 = request.POST.get("confirm_password")
        
        if password2 == password1:
           new_user = User.objects.create_user(username=username, email=email, first_name=fname, last_name=lname, password=password1)
           new_user.save()
        return redirect("home:login")
    return render(request, "home/register.html")

def logout_view(request):
    logout(request)
    return redirect("home:home")

home/views.py
from django.shortcuts import render

# Create your views here.

def home(request):
    return render(request, "home/index.html")

def about(request):
    return render(request, "home/about.html")

account/templates/home/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Ranzilia: Log in</title>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="css/login.css">
    <link rel="stylesheet" href="css/style.css">
    <link rel="stylesheet" href="css/design.css">
    <link rel="stylesheet" href="css/About.css">
</head>

<body>
    <div class="main-siteheader-1">
        <header class="siteheader-2">
            <div class="innerheader-3">
                <div class="siteNameContainer-4">
                    <h2 id="siteNme-5">Alest Food</h2>
                </div>
            </div>
        </header>
    </div>
    <section class="page-holder">
        <div class="container">
            <div class="inner-contents">
                <div class="login-picture-container">
                    <div class="login-picture-box"></div>
                </div>
                <div class="form-section">
                    <div class="inner-form-box">
                        <h2 class="log-holder">Log in</h2>
                        <form method="post">
                            {% csrf_token %}
                            <div class="input-text-holder">
                                <label for="username"><p class="input-text">username</p></label>
                                <input type="text" name="username" id="username" required>
                            </div>
                            <div>
                                <label for="password"><p class="input-text">password</p></label>
                                <input type="password" name="password" id="password" required>
                            </div>
                            <div class="auxiliary-holder">
                                <div class="check-input">
                                    <input type="checkbox" name="Remember me" id="Remember me" class="check"> Remember me
                                </div>
                                <div class="forgot-password-text">
                                    <a class="password-text" href="">Forgot Password</a>
                                </div>
                            </div>
                            <div class="login-button-container">
                                <button type="submit">Login</button>
                            </div>
                            <div class="sign-container">
                                <p>Don't have an account then <a class="signup" href="{% url 'accounts:register' %}">Sign up</a></p>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <p class="copyright">
        Alest © This website is design by <i class="fa fa-heart-o" aria-hidden="true"></i>Aniebiet Francis

    </p>
</body>

</html>

account/templates/home/logout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <h3>You've successfully logout</h3>
    <p>
        click here to <a href="{% url 'home:login' %}">login</a>
    </p>
</body>

</html>

account/templates/home/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Ranzilia: Sign up</title>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">


    <link rel="stylesheet" href="{% static 'home/css/login.css' %}">
    <link rel="stylesheet" href="{% static 'home/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'home/css/design.css' %}">
</head>

<body>
    <section class="form-holder">
        <div class="form">
            <div class="inside">
                <h2>Sign up</h2>
                <form method="post">
                    {% csrf_token %}
                    <div>
                        <label for="fname">First Name</label>
                        <input type="text" name="fname" id="fname" required>
                    </div><br>
                    <div>
                        <label for="lname">Last Name</label>
                        <input type="text" name="lname" id="lname" required>
                    </div><br>

                    <div>
                        <label for="email">Email</label>
                        <input type="email" name="email" id="email" required>
                    </div><br>
                    <div>
                        <label for="gender">Gender</label>
                        <select name="" id="">
                        <option value="">Select your gender</option>
                        <option value="">Male</option>
                        <option value="">Female</option>
                        <option value="">Others</option>
                    </select>
                    </div>
                    <div>
                        <label for="username">Username</label>
                        <input type="text" name="username" id="username" required>
                    </div><br>
                    <div>
                        <label for="password">Password</label>
                        <input type="password" name="password" id="password" required>
                    </div><br>
                    <div>
                        <label for="confirm_password">Confirm Password</label>
                        <input type="password" name="confirm_password" id="confirm_password" required>
                    </div><br>
                    <div>
                        <button type="submit">Register</button>
                    </div>
                    <div>
                        <p>Already have an account
                            <a href="{% url 'home:login' %}">login</a>
                        </p>
                    </div>
                </form>
            </div>
        </div>

        <div>
            <img class="image" src="{% static 'home/img/office.jpg' %}" alt="office item">
        </div>
    </section>

</body>

</html>

home/templates/home/about.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script>
        addEventListener("load", function() {
            setTimeout(hideURLbar, 0);
        }, false);

        function hideURLbar() {
            window.scrollTo(0, 1);
        }
    </script>
    <link rel="stylesheet" href="css/font-awesome.min.css">
    <link rel="stylesheet" href="css/owl.carousel.css" type="text/css">
    <link href="css/bootstrap.min.css" rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="css/style.css">
    <link rel="stylesheet" href="css/animate.css">
</head>

<body>
    <div class="main-siteheader">
        <header class="siteheader">
            <div class="innerheader">
                <div class="siteNameContainer">
                    <h2 id="siteNme">Alest Food</h2>
                </div>
                <div class="user-panel">
                    <a href="login.html" class="button siteFeatureItem">log in</a>
                </div>
                <div>
                    <form action="">
                        <div class="header-search">
                            <input type="search">
                            <a href="#"><i class="fa fa-search"></i></a>
                        </div>
                    </form>
                </div>
            </div>
        </header>
    </div>
    <div class="nav-holder">
        <nav class="nav-section">
            <div class="nav-switch">
                <i class="fa fa-bars"></i>
            </div>
            <ul class="main-menu">
                <li><a href="https://preview.colorlib.com/theme/foodblog/index.html">Home</a></li>
                <li><a href="https://preview.colorlib.com/theme/foodblog/about.html">About</a></li>
                <li><a href="https://preview.colorlib.com/theme/foodblog/recipes.html">Receipies</a></li>
                <li><a href="https://preview.colorlib.com/theme/foodblog/#">Reviews</a></li>
                <li><a href="https://preview.colorlib.com/theme/foodblog/contact.html">Contact</a></li>
            </ul>
            <div class="header-social">
                <a href="https://preview.colorlib.com/theme/foodblog/#"><i class="fa fa-facebook"></i></a>
                <a href="https://preview.colorlib.com/theme/foodblog/#"><i class="fa fa-twitter"></i></a>
                <a href="https://preview.colorlib.com/theme/foodblog/#"><i class="fa fa-linkedin"></i></a>
            </div>
        </nav>
    </div>
    <section class="page-top-section set-bg" data-setbg="img/image\ 9.jpg" style="background-image: url(img/image\ 9.jpg);">
        <div class="container">
            <h2>About us</h2>
        </div>
    </section>
    <section class="about-section spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 about-text">
                    <h2>About our great team</h2>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum nec varius dui. Suspendisse potenti. Vestibulum ac pellentesque tortor. Aenean congue sed metus in iaculis. Cras a tortor enim. Phasellus posuere vestibulum ipsum,
                        eget lobortis purus. Orci varius natoque penatibus et magni. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum nec varius dui. Suspendisse potenti. Vestibulum ac pellentesque tortor. Aenean congue sed metus in
                        iaculis. Cras a tortor enim. Phasellus posuere vestibulum ipsum, eget lobortis purus. Orci varius natoque penatibus et magni.</p>
                    <div class="site-btn">Read more</div>
                </div>
                <div class="col-lg-6">
                    <img src="img/xabout.jpg.pagespeed.ic.aa3PvQNs-o.webp" alt="" data-pagespeed-url-hash="1162979360" onload="pagespeed.CriticalImages.checkImageForCriticality(this);">
                </div>
            </div>
        </div>
    </section>
    <section class="facts-section">
        <div class="facts-warp">
            <div class="container">
                <div class="row">
                    <div class="col-lg-3 col-sm-6 fact-item">
                        <div class="fact-icon">
                            <img src="img/icon/x1.png.pagespeed.ic.IT0aUJYYjE.webp" alt="" data-pagespeed-url-hash="2711860934" onload="pagespeed.CriticalImages.checkImageForCriticality(this);">
                        </div>
                        <h2>1287</h2>
                        <p>Amazing receipies</p>
                    </div>
                    <div class="col-lg-3 col-sm-6 fact-item">
                        <div class="fact-icon">
                            <img src="img/icon/x2.png.pagespeed.ic.hCETdeTSg7.webp" alt="" data-pagespeed-url-hash="3006360855" onload="pagespeed.CriticalImages.checkImageForCriticality(this);">
                        </div>
                        <h2>25</h2>
                        <p>Wine pairings</p>
                    </div>
                    <div class="col-lg-3 col-sm-6 fact-item">
                        <div class="fact-icon">
                            <img src="img/icon/x3.png.pagespeed.ic.OvOwdLKNSR.webp" alt="" data-pagespeed-url-hash="3300860776" onload="pagespeed.CriticalImages.checkImageForCriticality(this);">
                        </div>
                        <h2>471</h2>
                        <p>Meat receipies</p>
                    </div>
                    <div class="col-lg-3 col-sm-6 fact-item">
                        <div class="fact-icon">
                            <img src="img/icon/x4.png.pagespeed.ic.OC6MWxuGwa.webp" alt="" data-pagespeed-url-hash="3595360697" onload="pagespeed.CriticalImages.checkImageForCriticality(this);">
                        </div>
                        <h2>326</h2>
                        <p>Desert receipies</p>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section class="newsletter-section spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 nl-text">
                    <h2>Subscribe to our newsletter</h2>
                    <form class="newsletter-form">
                        <input type="text" placeholder="Your E-mail">
                        <button class="site-btn">Subscribe</button>
                    </form>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum nec varius dui. Suspendisse potenti. Vestibulum ac pellentesque tortor. Aenean congue sed metus in iaculis. Cras a tortor enim. </p>
                </div>
                <div class="col-lg-6">
                    <img class="nl-sp-img" src="img/xnewslatter.png.pagespeed.ic.CfOOM0MJDN.webp" alt="" data-pagespeed-url-hash="3457452644" onload="pagespeed.CriticalImages.checkImageForCriticality(this);">
                </div>
            </div>
        </div>
    </section>
    <div class="gallery">
        <div class="gallery-slider owl-carousel owl-loaded owl-drag">
            <div class="owl-stage-outer">
                <div class="owl-stage" style="transform: translate3d(-1348px, 0px, 0px); transition: all 0s ease 0s; width: 4047px;">
                    <div class="owl-item cloned" style="width: 224.833px;">
                        <div class="gs-item set-bg" data-setbg="img/instagram/1.jpg" style="background-image: url(&quot;img/instagram/1.jpg&quot;); height: 224.828px;"></div>
                    </div>
                    <div class="owl-item cloned" style="width: 224.833px;">
                        <div class="gs-item set-bg" data-setbg="img/instagram/2.jpg" style="background-image: url(&quot;img/instagram/2.jpg&quot;); height: 224.828px;"></div>
                    </div>
                    <div class="owl-item cloned" style="width: 224.833px;">
                        <div class="gs-item set-bg" data-setbg="img/instagram/3.jpg" style="background-image: url(&quot;img/instagram/3.jpg&quot;); height: 224.828px;"></div>
                    </div>
                    <div class="owl-item cloned" style="width: 224.833px;">
                        <div class="gs-item set-bg" data-setbg="img/instagram/4.jpg" style="background-image: url(&quot;img/instagram/4.jpg&quot;); height: 224.828px;"></div>
                    </div>
                    <div class="owl-item cloned" style="width: 224.833px;">
                        <div class="gs-item set-bg" data-setbg="img/instagram/5.jpg" style="background-image: url(&quot;img/instagram/5.jpg&quot;); height: 224.828px;"></div>
                    </div>
                    <div class="owl-item cloned" style="width: 224.833px;">
                        <div class="gs-item set-bg" data-setbg="img/instagram/6.jpg" style="background-image: url(&quot;img/instagram/6.jpg&quot;); height: 224.828px;"></div>
                    </div>
                    <div class="owl-item active" style="width: 224.833px;">
                        <div class="gs-item set-bg" data-setbg="img/instagram/1.jpg" style="background-image: url(&quot;img/instagram/1.jpg&quot;); height: 224.828px;"></div>
                    </div>
                    <div class="owl-item active" style="width: 224.833px;">
                        <div class="gs-item set-bg" data-setbg="img/instagram/2.jpg" style="background-image: url(&quot;img/instagram/2.jpg&quot;); height: 224.828px;"></div>
                    </div>
                    <div class="owl-item active" style="width: 224.833px;">
                        <div class="gs-item set-bg" data-setbg="img/instagram/3.jpg" style="background-image: url(&quot;img/instagram/3.jpg&quot;); height: 224.828px;"></div>
                    </div>
                    <div class="owl-item active" style="width: 224.833px;">
                        <div class="gs-item set-bg" data-setbg="img/instagram/4.jpg" style="background-image: url(&quot;img/instagram/4.jpg&quot;); height: 224.828px;"></div>
                    </div>
                    <div class="owl-item active" style="width: 224.833px;">
                        <div class="gs-item set-bg" data-setbg="img/instagram/5.jpg" style="background-image: url(&quot;img/instagram/5.jpg&quot;); height: 224.828px;"></div>
                    </div>
                    <div class="owl-item active" style="width: 224.833px;">
                        <div class="gs-item set-bg" data-setbg="img/instagram/6.jpg" style="background-image: url(&quot;img/instagram/6.jpg&quot;); height: 224.828px;"></div>
                    </div>
                    <div class="owl-item cloned" style="width: 224.833px;">
                        <div class="gs-item set-bg" data-setbg="img/instagram/1.jpg" style="background-image: url(&quot;img/instagram/1.jpg&quot;); height: 224.828px;"></div>
                    </div>
                    <div class="owl-item cloned" style="width: 224.833px;">
                        <div class="gs-item set-bg" data-setbg="img/instagram/2.jpg" style="background-image: url(&quot;img/instagram/2.jpg&quot;); height: 224.828px;"></div>
                    </div>
                    <div class="owl-item cloned" style="width: 224.833px;">
                        <div class="gs-item set-bg" data-setbg="img/instagram/3.jpg" style="background-image: url(&quot;img/instagram/3.jpg&quot;); height: 224.828px;"></div>
                    </div>
                    <div class="owl-item cloned" style="width: 224.833px;">
                        <div class="gs-item set-bg" data-setbg="img/instagram/4.jpg" style="background-image: url(&quot;img/instagram/4.jpg&quot;); height: 224.828px;"></div>
                    </div>
                    <div class="owl-item cloned" style="width: 224.833px;">
                        <div class="gs-item set-bg" data-setbg="img/instagram/5.jpg" style="background-image: url(&quot;img/instagram/5.jpg&quot;); height: 224.828px;"></div>
                    </div>
                    <div class="owl-item cloned" style="width: 224.833px;">
                        <div class="gs-item set-bg" data-setbg="img/instagram/6.jpg" style="background-image: url(&quot;img/instagram/6.jpg&quot;); height: 224.828px;"></div>
                    </div>
                </div>
            </div>
            <div class="owl-nav disabled">
                <div class="owl-prev">prev</div>
                <div class="owl-next">next</div>
            </div>
            <div class="owl-dots disabled">
                <div class="owl-dot active"><span></span></div>
            </div>
        </div>
    </div>
    <footer class="footer-section set-bg" data-setbg="img/footer-bg.jpg" style="background-image: url(&quot;img/footer-bg.jpg&quot;);">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-6">
                    <div class="footer-logo">
                        <h2 id="siteNme">Alest Food</h2>
                    </div>
                    <div class="footer-social">
                        <a href="#"><i class="fa fa-pinterest"></i></a>
                        <a href="#"><i class="fa fa-facebook"></i></a>
                        <a href="#"><i class="fa fa-twitter"></i></a>
                        <a href="#"><i class="fa fa-linkedin"></i></a>
                    </div>
                </div>
                <div class="col-lg-6 text-lg-right">
                    <ul class="footer-menu">
                        <li><a href="#">Home</a></li>
                        <li><a href="#">Features</a></li>
                        <li><a href="#">Receipies</a></li>
                        <li><a href="#">Reviews</a></li>
                        <li><a href="#">Contact</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>
</body>

</html>